notifications:
  slack: swppblender2018:soN9EST68mFickJ8zWLpaFQL
matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      dist: trusty
      sudo: true
      cache:
        directories:
          - frontend/node_modules
      addons:
        chrome: stable
      branches:
        except:
          - /^temp\/.*$/
      before_install:
        - cd frontend
        - yarn global add @angular/cli
      install:
        - yarn
      script:
        - yarn lint
        - yarn test --karma-config src/karma-ci.conf.js --code-coverage

    - language: python
      python: 3.7
      dist: xenial
      before_install: 
        - cd backend
        - pip install pipenv
        - sudo apt-get update

      install:
        - sudo apt-get update -qq
        - sudo apt-get install -y libproj-dev libgeos-dev
        - sudo apt-get install -y libspatialite-dev libsqlite3-mod-spatialite gdal-bin
        - pipenv install --dev
      script:
        - cd kiwi
        - pipenv run pytest --cov kiorder/services --cov kiorder/models --cov kiorder/api

