matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      dist: trusty
      sudo: false
      cache:
        directories:
          - frontend/node_modules
      addons:
        chrome: stable
      branches:
        except:
          - /^temp\/.*$/
      before_install:
        - cd frontend
        - yarn global add @angular/cli
      install:
        - yarn
      script:
        - yarn lint
        - yarn test --karma-config src/karma-ci.conf.js --code-coverage

    - language: python
      python:
        - 3.7
      before_install: 
        - cd backend
        - pip install pipenv
        - pipenv install --dev
      install:
        - pipenv install --dev
      script:
        - cd kiwi
        - pipenv run pytest --cov kiorder/services --cov kiorder/models --cov kiorder/api

